version: '3.8'

services:
  model_train:
    build: ./model_train
    container_name: model_train  
    ports:
      - "5000:5000"  
    volumes:
      - ./model_train/models:/app/models
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin


